# Generated by Django 5.2.17 on 2026-10-07 15:54
"""
Schema for the new Blotter module (BlotterCase, BlotterParty, BlotterHearing).

Why this file is 0005 and not 0001: the live database still has django_migrations
rows for an old, removed blotter app (blotter 0001_initial .. 0004_*; its tables
were dropped). A new 0001_initial would be treated as already applied there and
the tables would never be created. Django ignores recorded migrations that are no
longer on disk, so starting at 0005 is safe on both fresh and existing databases.
"""

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0019_normalize_phone_numbers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlotterCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('incident_type', models.CharField(choices=[('dispute', 'Dispute'), ('noise', 'Noise complaint'), ('theft', 'Theft'), ('physical_injury', 'Physical injury'), ('property_damage', 'Property damage'), ('domestic', 'Domestic'), ('threat', 'Threat'), ('trespassing', 'Trespassing'), ('other', 'Other')], max_length=30)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('narrative', models.TextField()),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('under_mediation', 'Under mediation'), ('settled', 'Settled'), ('escalated', 'Escalated'), ('dismissed', 'Dismissed'), ('withdrawn', 'Withdrawn')], db_index=True, default='filed', max_length=20)),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('is_confidential', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blotter_cases_handled', to=settings.AUTH_USER_MODEL)),
                ('purok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blotter_cases', to='accounts.purok')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blotter_cases_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blotter Case',
                'verbose_name_plural': 'Blotter Cases',
                'ordering': ['-filed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BlotterHearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('outcome_notes', models.TextField(blank=True, default='')),
                ('complainant_attended', models.BooleanField(default=False)),
                ('respondent_attended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='blotter.blottercase')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blotter_hearings_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blotter Hearing',
                'verbose_name_plural': 'Blotter Hearings',
                'ordering': ['scheduled_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BlotterParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('complainant', 'Complainant'), ('respondent', 'Respondent'), ('witness', 'Witness')], max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('contact_no', models.CharField(blank=True, default='', max_length=20, validators=[apps.core.validators.PhMobileValidator()])),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='blotter.blottercase')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blotter_parties', to='accounts.resident')),
            ],
            options={
                'verbose_name': 'Blotter Party',
                'verbose_name_plural': 'Blotter Parties',
                'ordering': ['case', 'role', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='blottercase',
            index=models.Index(fields=['status', 'filed_at'], name='blotter_blo_status_0afd93_idx'),
        ),
        migrations.AddIndex(
            model_name='blottercase',
            index=models.Index(fields=['purok', 'status'], name='blotter_blo_purok_i_4b3c7e_idx'),
        ),
    ]
