# Generated by Django 5.2.17 on 2026-10-01 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], default='Single', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth for age & demographic classification', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_4ps',
            field=models.BooleanField(default=False, help_text='Pantawid Pamilyang Pilipino Program (4Ps) beneficiary', verbose_name='4Ps Beneficiary'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pwd',
            field=models.BooleanField(default=False, help_text='Person with Disability', verbose_name='PWD'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_senior',
            field=models.BooleanField(default=False, help_text='Senior Citizen (60+ years old)', verbose_name='Senior Citizen'),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, help_text='Primary occupation or livelihood', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='purok',
            field=models.CharField(blank=True, choices=[('Purok 1', 'Purok 1'), ('Purok 2', 'Purok 2'), ('Purok 3', 'Purok 3'), ('Purok 4', 'Purok 4'), ('Purok 5', 'Purok 5'), ('Purok 6', 'Purok 6'), ('Purok 7', 'Purok 7')], default='Purok 1', help_text='Purok jurisdiction inside the Barangay', max_length=20),
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_number', models.CharField(help_text='Unique Household Reference Number (e.g. HH-2026-001)', max_length=50, unique=True)),
                ('address', models.TextField(help_text='Full residential street / house number')),
                ('purok', models.CharField(choices=[('Purok 1', 'Purok 1'), ('Purok 2', 'Purok 2'), ('Purok 3', 'Purok 3'), ('Purok 4', 'Purok 4'), ('Purok 5', 'Purok 5'), ('Purok 6', 'Purok 6'), ('Purok 7', 'Purok 7')], default='Purok 1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head', models.ForeignKey(blank=True, help_text='Designated head of the family/household', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_households', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Household Record',
                'verbose_name_plural': 'Household Records (RBI)',
                'ordering': ['household_number'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='household',
            field=models.ForeignKey(blank=True, help_text='Assigned Household folder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.household'),
        ),
    ]
