# Generated by Django 5.2.17 on 2026-10-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_civil_status_user_date_of_birth_user_is_4ps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Resident or staff avatar photo', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='duty_return_date',
            field=models.DateField(blank=True, help_text='Expected return date if on leave', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='duty_status',
            field=models.CharField(choices=[('on_duty', 'On-Duty'), ('on_leave', 'On-Leave'), ('absent', 'Absent')], default='on_duty', help_text='Active officer roster duty status', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='status_message',
            field=models.CharField(blank=True, default='', help_text='Personal status message e.g. Available at Barangay Hall until 4 PM', max_length=255),
        ),
    ]
