# Generated by Django 5.2.17 on 2026-10-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar_user_duty_return_date_user_duty_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='duty_leave_reason',
            field=models.CharField(blank=True, default='', help_text='Official reason for leave if on-leave', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='duty_status',
            field=models.CharField(blank=True, choices=[('on_duty', 'On-Duty'), ('on_leave', 'On-Leave'), ('absent', 'Absent')], default='on_duty', help_text='Active officer roster duty status', max_length=20),
        ),
    ]
