# Generated by Django 5.2.17 on 2026-10-02 06:16
# Modified: non-atomic migration so each operation commits individually,
# allowing SQLite to transition the purok column from NOT NULL VARCHAR → FK.

import django.db.models.deletion
from django.conf import settings
from django.db import connection, migrations, models


PUROK_NAMES = [
    'Purok 1', 'Purok 2', 'Purok 3', 'Purok 4',
    'Purok 5', 'Purok 6', 'Purok 7',
]


def seed_puroks(apps, schema_editor):
    """Create one Purok row per zone so the FK conversion succeeds."""
    Purok = apps.get_model('accounts', 'Purok')
    for name in PUROK_NAMES:
        Purok.objects.get_or_create(name=name)


def clear_purok_values(apps, schema_editor):
    """
    Rebuild the accounts_user and accounts_household tables without the
    NOT NULL constraint on purok, and NULL out the value.
    SQLite does not support ALTER COLUMN, so we use the standard
    table-rebuild pattern (CREATE temp → INSERT → DROP → RENAME).
    """
    with connection.cursor() as cursor:
        cursor.execute("PRAGMA foreign_keys = OFF")

        # ── accounts_user: rebuild to drop NOT NULL on purok ──────────────
        # Get the current CREATE TABLE statement
        cursor.execute(
            "SELECT sql FROM sqlite_master WHERE type='table' AND name='accounts_user'"
        )
        row = cursor.fetchone()
        if row:
            create_sql = row[0]
            # Replace the NOT NULL constraint on purok (varchar(20) NOT NULL)
            create_sql_fixed = create_sql.replace(
                '"purok" varchar(20) NOT NULL',
                '"purok" varchar(20) NULL'
            )
            if '"purok" varchar(20) NOT NULL' in create_sql:
                cursor.execute(create_sql_fixed.replace(
                    'CREATE TABLE "accounts_user"',
                    'CREATE TABLE "_tmp_accounts_user"'
                ))
                cursor.execute(
                    'INSERT INTO "_tmp_accounts_user" SELECT * FROM "accounts_user"'
                )
                cursor.execute('DROP TABLE "accounts_user"')
                cursor.execute('ALTER TABLE "_tmp_accounts_user" RENAME TO "accounts_user"')
                cursor.execute('UPDATE accounts_user SET purok = NULL')

        # ── accounts_household: rebuild to drop NOT NULL on purok ─────────
        cursor.execute(
            "SELECT sql FROM sqlite_master WHERE type='table' AND name='accounts_household'"
        )
        row = cursor.fetchone()
        if row:
            create_sql = row[0]
            create_sql_fixed = create_sql.replace(
                '"purok" varchar(20) NOT NULL',
                '"purok" varchar(20) NULL'
            )
            if '"purok" varchar(20) NOT NULL' in create_sql:
                cursor.execute(create_sql_fixed.replace(
                    'CREATE TABLE "accounts_household"',
                    'CREATE TABLE "_tmp_accounts_household"'
                ))
                cursor.execute(
                    'INSERT INTO "_tmp_accounts_household" SELECT * FROM "accounts_household"'
                )
                cursor.execute('DROP TABLE "accounts_household"')
                cursor.execute('ALTER TABLE "_tmp_accounts_household" RENAME TO "accounts_household"')
                cursor.execute('UPDATE accounts_household SET purok = NULL')

        cursor.execute("PRAGMA foreign_keys = ON")


class Migration(migrations.Migration):

    # non-atomic so each AlterField commits separately — required for SQLite
    # table-rebuild workaround (cannot ALTER COLUMN in SQLite).
    atomic = False

    dependencies = [
        ('accounts', '0004_user_duty_leave_reason_alter_user_duty_status'),
    ]

    operations = [
        # Step 1: Create the Purok lookup table
        migrations.CreateModel(
            name='Purok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Purok 1, Purok 2 \u2026 Purok 7', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional zone description or boundary notes', max_length=255)),
            ],
            options={
                'verbose_name': 'Purok',
                'verbose_name_plural': 'Puroks',
                'ordering': ['name'],
            },
        ),

        # Step 2: Seed the 7 Purok rows
        migrations.RunPython(seed_puroks, migrations.RunPython.noop),

        # Step 3: Rebuild tables to allow NULL on purok, then clear values
        migrations.RunPython(clear_purok_values, migrations.RunPython.noop),

        # Step 4: Schema changes on Household
        migrations.RemoveField(
            model_name='household',
            name='address',
        ),
        migrations.AddField(
            model_name='household',
            name='street_address',
            field=models.CharField(default='', help_text='House/Unit number and street name only (e.g. 12-B Rizal St.)', max_length=255),
            preserve_default=False,
        ),

        # Step 5: Add street_address to User
        migrations.AddField(
            model_name='user',
            name='street_address',
            field=models.CharField(blank=True, help_text='House/Unit number and street name (e.g. 22 Mabini St.)', max_length=255),
        ),

        # Step 6: Relabel old address field as LEGACY
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='[LEGACY] Full residential address \u2014 use street_address + purok instead.'),
        ),

        # Step 7: Convert purok CharField → FK (values are already NULL)
        migrations.AlterField(
            model_name='household',
            name='purok',
            field=models.ForeignKey(
                blank=True,
                help_text='Purok zone this household belongs to',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='households',
                to='accounts.purok',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='purok',
            field=models.ForeignKey(
                blank=True,
                help_text='Purok jurisdiction inside the Barangay',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='residents',
                to='accounts.purok',
            ),
        ),
    ]
