# Generated by Django 5.2.17 on 2026-10-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_apply_nf_schema_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='household',
        ),
        migrations.DeleteModel(
            name='Household',
        ),
    ]
