# Generated by Django 5.2.17 on 2026-10-04 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_must_change_password_user_reviewed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('purok', 'Purok Jurisdiction'), ('service_area', 'Service Area')], max_length=30)),
                ('scope_value', models.CharField(help_text='e.g. Purok 1, Health, Documents, Peace and Order', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_assignments', to='accounts.officer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Assignment',
                'verbose_name_plural': 'Staff Assignments',
                'ordering': ['user', 'scope_type', 'scope_value'],
            },
        ),
        migrations.CreateModel(
            name='PermissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(help_text='e.g. appointments, communications, accounts', max_length=50)),
                ('action', models.CharField(help_text='e.g. view, create, edit, approve, reject, delete, message, post_category', max_length=50)),
                ('allowed', models.BooleanField(default=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_rules', to='accounts.officer')),
            ],
            options={
                'verbose_name': 'Permission Rule',
                'verbose_name_plural': 'Permission Rules',
                'ordering': ['officer', 'module', 'action'],
                'unique_together': {('officer', 'module', 'action')},
            },
        ),
    ]
