# Generated by Django 5.2.17 on 2026-10-05 00:58

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_staffassignment_permissionrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='id_photo',
            field=models.FileField(blank=True, help_text='Resident identity document (stored in private storage)', null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PureWindowsPath('C:/brgy/private_media/id_photos')), upload_to=''),
        ),
    ]
