# Generated by Django 5.2.17 on 2026-10-05 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_resident_id_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='consent_recorded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='consent_recorded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='needs_categories',
            field=models.CharField(blank=True, default='', help_text='senior, pwd, low_income, other', max_length=150),
        ),
        migrations.AddField(
            model_name='resident',
            name='needs_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resident',
            name='needs_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='needs_recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_needs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resident',
            name='contact_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='resident',
            name='needs_attention',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_name', models.CharField(blank=True, default='', max_length=150)),
                ('address', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_households', to='accounts.resident')),
                ('purok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to='accounts.purok')),
            ],
            options={
                'verbose_name': 'Household',
                'verbose_name_plural': 'Households',
                'ordering': ['purok', 'household_name', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='resident',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.household'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['purok', 'needs_attention'], name='accounts_re_purok_i_64830e_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['needs_attention'], name='accounts_re_needs_a_b8b28e_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['is_archived'], name='accounts_re_is_arch_fa4549_idx'),
        ),
    ]
