# Generated by Django 5.2.17 on 2026-10-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_resident_consent_recorded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Barangay Poblacion', max_length=150)),
                ('address', models.TextField(blank=True, default='Barangay Hall, Main Street')),
                ('contact_no', models.CharField(blank=True, default='(02) 8123-4567', max_length=50)),
                ('office_hours', models.CharField(blank=True, default='Monday - Friday, 8:00 AM - 5:00 PM', max_length=120)),
                ('venue', models.CharField(blank=True, default='Barangay Session Hall', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='barangay/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Barangay Information',
                'verbose_name_plural': 'Barangay Information',
            },
        ),
        migrations.AddField(
            model_name='resident',
            name='no_consent_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for recording needs without consent'),
        ),
        migrations.AddField(
            model_name='staffassignment',
            name='term_end',
            field=models.DateField(blank=True, help_text='End of assignment term', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='term_end',
            field=models.DateField(blank=True, help_text='End of appointment or elective term', null=True),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['last_name', 'first_name'], name='accounts_re_last_na_d9ac93_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['birthdate'], name='accounts_re_birthda_df5137_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['created_at'], name='accounts_re_created_a19150_idx'),
        ),
    ]
