# Generated by Django 5.2.17 on 2026-10-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_drop_user_demographics'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangayinfo',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='barangayinfo',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
