# Generated by Django 5.2.17 on 2026-10-07 14:15

import apps.core.uploads
import apps.core.validators
import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_seed_statistics_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='contact_no',
            field=models.CharField(blank=True, default='', max_length=20, validators=[apps.core.validators.PhMobileValidator()]),
        ),
        migrations.AlterField(
            model_name='resident',
            name='id_photo',
            field=models.FileField(blank=True, help_text='Resident identity document (stored in private storage)', null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PureWindowsPath('C:/brgy/private_media/id_photos')), upload_to=apps.core.uploads.RandomUploadTo('id'), validators=[apps.core.uploads.UploadValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, validators=[apps.core.validators.PhMobileValidator()]),
        ),
    ]
