# Generated by Django 5.2.17 on 2026-10-01 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Detailed announcement content (supports Markdown formatting)')),
                ('category', models.CharField(choices=[('general', 'General Advisory'), ('event', 'Community Event'), ('emergency', 'Emergency Alert'), ('health', 'Health & Sanitation'), ('ordinance', 'Barangay Ordinance')], default='general', max_length=30)),
                ('image', models.ImageField(blank=True, help_text='Optional header image or poster', null=True, upload_to='announcements/')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin to top of resident feeds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement & Feed',
                'verbose_name_plural': 'Announcements & Feeds',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KapitanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('on_duty', 'On Duty'), ('on_leave', 'On Leave')], default='on_duty', max_length=20)),
                ('leave_reason', models.TextField(blank=True, help_text='Reason for leave (required when setting to On Leave)')),
                ('return_date', models.DateField(blank=True, help_text='Expected date of return to barangay service', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kapitan_status_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kapitan Status',
                'verbose_name_plural': 'Kapitan Status Records',
                'ordering': ['-updated_at'],
            },
        ),
    ]
