# Generated by Django 5.2.17 on 2026-10-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegislativeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Ordinance', 'Ordinance'), ('Resolution', 'Resolution'), ('Executive Order', 'Executive Order')], default='Ordinance', max_length=50)),
                ('document_number', models.CharField(help_text='e.g. Ord. No. 2026-04 or Res. No. 12-S2026', max_length=100)),
                ('date_approved', models.DateField(help_text='Date when enacted or signed')),
                ('pdf_file', models.FileField(blank=True, help_text='Upload official signed copy', null=True, upload_to='legislative/')),
                ('summary', models.TextField(help_text='Concise summary or purpose of the measure')),
                ('is_public', models.BooleanField(default=True, help_text='Display publicly on the Transparency Portal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legislative Record',
                'verbose_name_plural': 'Legislative Records & Transparency',
                'ordering': ['-date_approved', '-created_at'],
            },
        ),
    ]
