# Generated by Django 5.2.17 on 2026-10-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_alter_announcement_category_postcomment_postreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('announcement', 'ANNOUNCEMENT'), ('emergency', 'EMERGENCY ALERT'), ('event', 'UPCOMING EVENT'), ('scholarship', 'SCHOLARSHIP'), ('donation', 'DONATION'), ('legislative', 'LEGISLATIVE (ORDINANCE/EO)'), ('general', 'GENERAL ADVISORY'), ('health', 'HEALTH & SANITATION'), ('ordinance', 'BARANGAY ORDINANCE')], default='announcement', max_length=30),
        ),
    ]
