# Generated by Django 5.2.17 on 2026-10-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_postcategory_post_announcement_category_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kapitanstatus',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='LegislativeRecord',
        ),
        migrations.DeleteModel(
            name='KapitanStatus',
        ),
    ]
