# Generated by Django 5.2.17 on 2026-10-05 01:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_resident_id_photo'),
        ('communications', '0006_remove_kapitanstatus_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='audience_type',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('purok', 'Specific Purok')], db_index=True, default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='purok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='accounts.purok'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('done', 'Done'), ('expired', 'Expired')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='announcement',
            name='valid_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('health', 'Health'), ('emergency', 'Emergency Alert'), ('education', 'Education'), ('event', 'Upcoming Event'), ('concern', 'Concern for Street'), ('general', 'General Advisory'), ('scholarship', 'Scholarship'), ('donation', 'Donation'), ('legislative', 'Legislative (Ordinance/EO)'), ('ordinance', 'Barangay Ordinance')], db_index=True, default='announcement', max_length=30),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
