# Generated by Django 5.2.17 on 2026-10-05 01:56

import apps.communications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_backfill_existing_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional header image or poster', null=True, upload_to=apps.communications.models.post_image_upload_path),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('done', 'Done'), ('expired', 'Expired'), ('archived', 'Archived')], db_index=True, default='active', max_length=20),
        ),
    ]
