# Generated by Django 5.2.17 on 2026-10-05 03:04

from django.db import migrations, models


def populate_slugs(apps, schema_editor):
    from django.utils.text import slugify
    PostCategory = apps.get_model('communications', 'PostCategory')
    for cat in PostCategory.objects.all():
        base_slug = slugify(cat.name).replace('-', '_') or f"cat_{cat.id}"
        slug = base_slug
        counter = 1
        while PostCategory.objects.filter(slug=slug).exclude(id=cat.id).exists():
            slug = f"{base_slug}_{counter}"
            counter += 1
        cat.slug = slug
        if cat.name.lower() in ['health', 'emergency alert', 'emergency']:
            cat.is_system = True
        cat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_alter_announcement_image_alter_announcement_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Post Category', 'verbose_name_plural': 'Post Categories'},
        ),
        migrations.AddField(
            model_name='postcategory',
            name='default_end',
            field=models.CharField(choices=[('end_of_month', 'End of Month'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='expires',
            field=models.BooleanField(default=True, help_text='Whether posts in this category can expire'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System categories cannot be deleted'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='notify_on_post',
            field=models.BooleanField(default=False, help_text='Send notification broadcast on publish'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=60),
        ),
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
