# Generated by Django 5.2.17 on 2026-10-04 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('email_type', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Dispatch Log',
                'verbose_name_plural': 'Email Dispatch Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('complete', 'Complete'), ('no_show', 'No-Show'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default='approve', max_length=30)),
                ('action_type', models.CharField(help_text='e.g. Resident Registration, Appointment, Document Issuance', max_length=100)),
                ('target_id', models.CharField(blank=True, default='', max_length=100)),
                ('target_name', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.TextField(blank=True, default='', help_text='State of rejection, remarks, or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity & Audit Log',
                'verbose_name_plural': 'Activity & Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
