# Generated by Django 5.2.17 on 2026-10-01 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('clearance', 'Barangay Clearance'), ('residency', 'Certificate of Residency'), ('indigency', 'Certificate of Indigency'), ('noa', 'Notice of Award (NOA)')], max_length=50)),
                ('purpose', models.TextField(help_text='State clearly the purpose of this request (e.g. Employment, Scholarship, Postal ID)')),
                ('preferred_date', models.DateField(help_text='Selected date for processing or appointment')),
                ('preferred_time_slot', models.CharField(choices=[('morning', 'Morning (8:00 AM - 11:30 AM)'), ('afternoon', 'Afternoon (1:00 PM - 4:30 PM)')], default='morning', max_length=20)),
                ('supporting_id', models.ImageField(blank=True, help_text='Upload any supporting document or identification', null=True, upload_to='appointments/supporting_docs/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved_scheduled', 'Approved / Scheduled'), ('ready_for_pickup', 'Ready for Pickup'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='submitted', max_length=30)),
                ('admin_notes', models.TextField(blank=True, help_text='Administrative remarks, scheduled instructions, or reasons for rejection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_appointments', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Appointment',
                'verbose_name_plural': 'Document Appointments',
                'ordering': ['-created_at'],
            },
        ),
    ]
