# Generated by Django 5.2.17 on 2026-10-01 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedDocumentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(help_text='Official clearance tracking ID (e.g. BRGY-2026-0001)', max_length=60, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issued_log', to='appointments.appointment')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_documents', to=settings.AUTH_USER_MODEL)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issued Document Clearance Log',
                'verbose_name_plural': 'Issued Document Clearance Logs',
                'ordering': ['-issued_at'],
            },
        ),
    ]
