# Generated by Django 5.2.17 on 2026-10-02 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_issueddocumentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCareService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the health care service', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the health service offered')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this service is active and bookable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Health Care Service',
                'verbose_name_plural': 'Health Care Services',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Appointment Request', 'verbose_name_plural': 'Appointment Requests'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='category',
            field=models.CharField(choices=[('document', 'Document Request'), ('healthcare', 'Health Care Request')], default='document', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='document_type',
            field=models.CharField(blank=True, choices=[('clearance', 'Barangay Clearance'), ('residency', 'Certificate of Residency'), ('indigency', 'Certificate of Indigency'), ('noa', 'Notice of Award (NOA)')], default='clearance', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='purpose',
            field=models.TextField(help_text='State clearly the purpose of this request (e.g. Employment, Scholarship, Consultation notes)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='healthcare_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.healthcareservice'),
        ),
    ]
