# Generated by Django 5.2.17 on 2026-10-02 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_healthcareservice_alter_appointment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='resident',
            field=models.ForeignKey(help_text='The registered resident who submitted this request', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
