# Generated by Django 5.2.17 on 2026-10-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_applicant_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the document type (e.g. Barangay Clearance)', max_length=150, unique=True)),
                ('code', models.CharField(blank=True, default='', help_text='Short code identifier', max_length=50)),
                ('description', models.TextField(blank=True, default='', help_text='Description or purpose of this document')),
                ('requirements_needed', models.TextField(blank=True, default='', help_text='Default requirements needed')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='healthcareservice',
            name='available_date',
            field=models.CharField(blank=True, default='', help_text='Days or dates available (e.g. Mon, Wed, Fri or 2026-10-15)', max_length=120),
        ),
        migrations.AddField(
            model_name='healthcareservice',
            name='available_time',
            field=models.CharField(blank=True, default='', help_text='Operating hours or time window (e.g. 8:00 AM - 12:00 PM)', max_length=120),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='document_type',
            field=models.CharField(blank=True, choices=[('clearance', 'Barangay Clearance'), ('residency', 'Certificate of Residency'), ('indigency', 'Certificate of Indigency'), ('noa', 'Notice of Award (NOA)')], default='clearance', max_length=150),
        ),
    ]
