# Generated by Django 5.2.17 on 2026-10-03 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_documenttype_healthcareservice_available_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareservice',
            name='is_free',
            field=models.BooleanField(default=True, help_text='Designates whether this service is completely free on this day and time'),
        ),
        migrations.CreateModel(
            name='HealthSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(blank=True, help_text='Date of schedule', null=True)),
                ('time_window', models.CharField(choices=[('morning', 'Morning (8:00 AM - 11:30 AM)'), ('afternoon', 'Afternoon (1:00 PM - 4:30 PM)')], default='morning', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=20, help_text='Max slots available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='appointments.healthcareservice')),
            ],
            options={
                'verbose_name': 'Health Schedule',
                'verbose_name_plural': 'Health Schedules',
                'ordering': ['service_date', 'time_window'],
            },
        ),
    ]
