# Generated by Django 5.2.17 on 2026-10-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_healthcareservice_is_free_healthschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved_scheduled', 'Approved / Scheduled'), ('ready_for_pickup', 'Ready for Pickup'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('no_show', 'No-Show')], default='submitted', max_length=30),
        ),
    ]
