# Generated by Django 5.2.17 on 2026-10-05 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_issueddocumentlog_issued_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the required document or item', max_length=200)),
            ],
            options={
                'verbose_name': 'Requirement',
                'verbose_name_plural': 'Requirements',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='appt_date',
            field=models.DateField(blank=True, db_index=True, help_text='Standardized appointment date', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='document_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_fk', to='appointments.documenttype'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='health_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_service_appointments', to='appointments.healthcareservice'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='purpose_notes',
            field=models.TextField(blank=True, default='', help_text='Purpose notes for the appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reference_no',
            field=models.CharField(blank=True, db_index=True, help_text='Unique appointment reference number (e.g. APT-2026-0001)', max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for rejection if status is rejected'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_window',
            field=models.CharField(choices=[('morning', 'Morning (8:00 AM - 11:30 AM)'), ('afternoon', 'Afternoon (1:00 PM - 4:30 PM)')], default='morning', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved_scheduled', 'Approved / Scheduled'), ('ready_for_pickup', 'Ready for Pickup'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('no_show', 'No-Show')], default='pending', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='healthschedule',
            unique_together={('health_service', 'service_date', 'time_window')},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'appt_date'], name='appointment_status_98d565_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'preferred_date'], name='appointment_status_4ac55f_idx'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='appointments.documenttype'),
        ),
    ]
