# Generated by Django 5.2.17 on 2026-10-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_requirement_appointment_appt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='preferred_date',
            field=models.DateField(help_text='DEPRECATED: Use appt_date instead. Selected date for processing or appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='preferred_time_slot',
            field=models.CharField(choices=[('morning', 'Morning (8:00 AM - 11:30 AM)'), ('afternoon', 'Afternoon (1:00 PM - 4:30 PM)')], default='morning', help_text='DEPRECATED: Use time_window instead. Choice of time slot', max_length=20),
        ),
    ]
