# Generated by Django 5.2.17 on 2026-10-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_migrate_legacy_appointment_statuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Document Type', 'verbose_name_plural': 'Document Types'},
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Requirement', 'verbose_name_plural': 'Requirements'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='fee_at_booking',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee captured at the time of booking', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fee for this document type', max_digits=10),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requirement',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('no_show', 'No-Show')], default='pending', max_length=30),
        ),
    ]
