# Generated by Django 5.2.17 on 2026-10-07 14:15

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_backfill_fee_at_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='applicant_phone',
            field=models.CharField(blank=True, default='', help_text='11-digit mobile number, 09XXXXXXXXX', max_length=20, validators=[apps.core.validators.PhMobileValidator()]),
        ),
    ]
