# Generated by Django 5.2.17 on 2026-10-07 14:16

import apps.appointments.models
import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_normalize_applicant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='supporting_id',
            field=models.FileField(blank=True, help_text='Supporting document or ID (JPG, PNG, WEBP or PDF, max 5 MB)', null=True, storage=apps.appointments.models.private_supporting_storage, upload_to=apps.core.uploads.RandomUploadTo('appointments/supporting_docs'), validators=[apps.core.uploads.UploadValidator()]),
        ),
    ]
