# Generated by Django 5.2.17 on 2026-10-05 01:59

import apps.chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.chat.models.chat_attachment_upload_path),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_mime',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_type', models.CharField(choices=[('concern', 'Resident Concern / Ticket'), ('direct', 'Direct Message')], db_index=True, default='direct', max_length=20)),
                ('status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('seen', 'Seen'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], db_index=True, default=None, help_text='Status for concerns only. Null for direct messages.', max_length=20, null=True)),
                ('category', models.CharField(blank=True, choices=[('health', 'Health & Medical Services'), ('peace_and_order', 'Peace, Order & Tanod'), ('education', 'Education, Youth & Scholarship'), ('infrastructure', 'Infrastructure & Public Works'), ('general', 'General Community Concern')], db_index=True, default='', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_concerns', to=settings.AUTH_USER_MODEL)),
                ('direct_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_message_threads', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_threads', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Thread / Concern',
                'verbose_name_plural': 'Chat Threads / Concerns',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatthread'),
        ),
    ]
