# Generated by Django 5.2.17 on 2026-10-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_attachment_message_attachment_filename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcernCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Concern Category',
                'verbose_name_plural': 'Concern Categories',
                'ordering': ['name'],
            },
        ),
    ]
