# Generated by Django 5.2.17 on 2026-10-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_concerncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='concerncategory',
            name='routing_target_type',
            field=models.CharField(choices=[('service_area', 'Service Area'), ('committee', 'Committee')], default='service_area', max_length=20),
        ),
        migrations.AddField(
            model_name='concerncategory',
            name='routing_target_value',
            field=models.CharField(blank=True, default='', help_text='Name of assigned service area or committee', max_length=100),
        ),
    ]
